// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUm7Rzijr4C5ji0kUQ8NyFQM1LbFD6Oqg',
    appId: '1:168275129680:web:87e916a1923892949ba855',
    messagingSenderId: '168275129680',
    projectId: 'login-7d663',
    authDomain: 'login-7d663.firebaseapp.com',
    storageBucket: 'login-7d663.firebasestorage.app',
    measurementId: 'G-SVPLP3H4QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBslnsl0ymVdq_t7Whkd7O6o4JIXGEDUy4',
    appId: '1:168275129680:android:4e43d09df95ec07b9ba855',
    messagingSenderId: '168275129680',
    projectId: 'login-7d663',
    storageBucket: 'login-7d663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYo_9Pt8GfANoF_JQJonD9FIXYIcGlwhE',
    appId: '1:168275129680:ios:51f6c2ca73e563da9ba855',
    messagingSenderId: '168275129680',
    projectId: 'login-7d663',
    storageBucket: 'login-7d663.firebasestorage.app',
    iosBundleId: 'com.example.unaAgendamento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYo_9Pt8GfANoF_JQJonD9FIXYIcGlwhE',
    appId: '1:168275129680:ios:51f6c2ca73e563da9ba855',
    messagingSenderId: '168275129680',
    projectId: 'login-7d663',
    storageBucket: 'login-7d663.firebasestorage.app',
    iosBundleId: 'com.example.unaAgendamento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUm7Rzijr4C5ji0kUQ8NyFQM1LbFD6Oqg',
    appId: '1:168275129680:web:b5346220b6474cbd9ba855',
    messagingSenderId: '168275129680',
    projectId: 'login-7d663',
    authDomain: 'login-7d663.firebaseapp.com',
    storageBucket: 'login-7d663.firebasestorage.app',
    measurementId: 'G-FWY60GT053',
  );
}
